version: '3.9'
services:
  front:
    build: ./front
    working_dir: /app-frontend
    container_name: frontReact
    ports:
      - "3000:3000"
    restart: 'always'
  back:
    build: ./back
    container_name: backApi
    working_dir: /app-backend
    ports:
      - "3001:3001"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: 'always'
  db:
    image: mongo
    working_dir: /app-db
    container_name: dbMongo
    ports:
      - "3002:27017"
    restart: 'always'
    volumes:
      - ./db:/app-db